apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia
spec:
  replicas: 10
  selector:
    matchLabels:
      app: conversao
  template:
    metadata:
      labels:
        app: conversao
    spec:
      containers:
        - name: web
          image: fabricioveronez/bootcamp-conversao-distancia:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-service
spec:
  selector:
    app: conversao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
